use_frameworks!

target 'Cherry_Example' do
  pod 'Cherry', :path => '../'

  target 'Cherry_Tests' do
    inherit! :search_paths

    
  end
end

target 'Cherry' do
  pod 'Alamofire'
  pod 'PromisesSwift'
  
end
